spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/challenge_db
    username: user
    password: password
    show-sql: true
  jpa:
    properties:
      hibernate:
        format_sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
queue:
  name: votingResult

server:
  servlet:
    context-path: /api/v1/challenge-service
  port: 7001

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        jdbc:
          core:
            StatementCreatorUtils: TRACE
            JdbcTemplate: DEBUG
