version: '3.2'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: challenge_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
  rabbitmq:
    image: rabbitmq:3-management-alpine
    command: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"